### ISSUE TITLE
Game Crash on MouseClick event (Mod Menu Save&Back Button) Fabric 1.21.1 on 0.16.7

### ISSUE THREAD

**Issue by suerion** [connorslade/auto-reauth#5]
Hey, i had an Issue on my Testserver, on clicking Save&Back Button, my Client Crash with this Crash Issue

https://mclo.gs/lCpFMjc

If i should test Something, say it, this is only an test enviroment

Latest. Log (Client is not Optimized yet)
https://mclo.gs/bkUEINq

**Comment by suerion** [comment]
```
[21:25:12] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at knot/net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at knot/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1041.method_15998(class_1041.java:303) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1307) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.base/java.util.Optional.of(Optional.java:113) ~[?:?]
	at knot/com.connorcode.autoreauth.Config.save(Config.java:49) ~[auto-reauth-0.2.0-1.21.1.jar:?]
	at knot/com.connorcode.autoreauth.gui.ConfigScreen.lambda$init$0(ConfigScreen.java:37) ~[auto-reauth-0.2.0-1.21.1.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 16 more
	```

**Comment by connorslade** [comment]
Looks like this is happening because I accidentally used `Optional.of` instead of `Optional.ofNullable`. The crash happens when it tries to save your login token, but you haven't yet signed in.

Ill try to fix this and upload a new version in the next day or so.

**Comment by suerion** [comment]
Okey, yeah no problem :)

**Comment by connorslade** [comment]
I just made new releases on GitHub, Modrinth, and Curse Forge. Let me know if you encounter any other issues.

**Comment by suerion** [comment]
thanks, i will test it tomorow
